# Generated by Django 6.0.2 on 2026-02-05 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilArmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, choices=[('SCZ', 'Santa Cruz'), ('LPZ', 'La Paz'), ('CBBA', 'Cochabamba'), ('CHQ', 'Chuquisaca'), ('TJA', 'Tarija'), ('ORU', 'Oruro'), ('PTS', 'Potosí'), ('BEN', 'Beni'), ('PND', 'Pando')], max_length=4)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('spotify', models.CharField(blank=True, max_length=100)),
                ('bias_favorito', models.CharField(blank=True, help_text='Tu miembro favorito de BTS', max_length=100)),
                ('ocupacion', models.CharField(blank=True, max_length=200)),
                ('sobre_mi', models.TextField(blank=True, help_text='Cuéntanos algo sobre ti')),
                ('celular', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+591 12345678'", regex='^\\+?1?\\d{8,15}$')])),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_army', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil ARMY',
                'verbose_name_plural': 'Perfiles ARMY',
                'db_table': 'army_perfilarmy',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='army.perfilarmy')),
            ],
            options={
                'verbose_name': 'Lista Personal',
                'verbose_name_plural': 'Listas Personales',
                'db_table': 'army_listapersonal',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='army.perfilarmy')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'db_table': 'army_fotogaleria',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
