# Generated by Django 6.0.2 on 2026-02-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fotogaleria',
            table='_army__fotogaleria',
        ),
        migrations.AlterModelTable(
            name='listapersonal',
            table='_army__listapersonal',
        ),
        migrations.AlterModelTable(
            name='perfilarmy',
            table='_army__perfilarmy',
        ),
    ]
