# Generated by Django 6.0.2 on 2026-02-06 15:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army', '0002_alter_fotogaleria_table_alter_listapersonal_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotogaleria',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='perfilarmy',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
